server:
  port: 18085

spring:
  application:
    name: service-turbine

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  app-config: user-server,resource-server     # 指定要监控的应用服务名字 多个使用","分割,
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true  # 表示同一主机上的服务通过host和port的组合来进行区分，默认情况下是使用host来区分，这样会使本地调试有问题
  instanceUrlSuffix:
    default: /actuator/hystrix.stream



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/