
server:
  port: 18083

spring:
  application:
    name: user-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18080/eureka/



# 开启断路器
feign:
    hystrix:
        enabled: true
